using System.Globalization;
using B.DatabaseUtils.DuckDb.Configuration;
using B.EnumUtils;
using Casascius.Coins;
using CasasciusHelper.Core.Configuration;
using CasasciusHelper.Database;
using CasasciusHelper.Database.Entities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace CasasciusHelper.Core.Data.Import;

/// <summary>
/// Importer of CSV data files generated by Casascius Tracker (https://casasciustracker.com/)
/// </summary>
public interface ICasasciusTrackerCsvReader
{
    /// <inheritdoc cref="CasasciusTrackerCsvReader.ImportStreamUsingTempFile(Stream,CancellationToken)"/>
    Task<bool> ImportStreamUsingTempFile(Stream stream, CancellationToken cancellationToken = default);

    /// <inheritdoc cref="CasasciusTrackerCsvReader.DownloadAndImportLatestSnapshot(CancellationToken)"/>
    Task<bool> DownloadAndImportLatestSnapshot(CancellationToken cancellationToken = default);

    /// <inheritdoc cref="CasasciusTrackerCsvReader.ImportStream(Stream,CancellationToken)"/>
    [Obsolete]
    Task ImportStream(Stream stream, CancellationToken cancellationToken = default);
}

/// <inheritdoc cref="ICasasciusTrackerCsvReader"/>
public class CasasciusTrackerCsvReader : ICasasciusTrackerCsvReader
{
    private const string DEFAULT_DATA_CSV_NAME = "CasasciusTracker_ExportSnapshot.csv.tmp";
    private const string EXPECTED_CSV_FILE_HEADER = "Index,Address,Series,Type,Status,Value,Balance,Create Block,Redeem Block,Create Time,Redeem Time,Update Time";
    private const int EXPECTED_CSV_COLUMNS_NUMBER = 12;

    private readonly IOptions<ApplicationSettings> applicationSettings;
    private readonly IDuckDbAdoQueriesRunner adoQueriesRunner;
    private readonly IDuckDbDapperQueriesRunner dapperQueriesRunner;
    private readonly IHttpClientFactory httpClientFactory;
    private readonly ILogger<CasasciusTrackerCsvReader> logger;

    public CasasciusTrackerCsvReader(
        IOptions<ApplicationSettings> applicationSettings,
        IDuckDbAdoQueriesRunner adoQueriesRunner,
        IDuckDbDapperQueriesRunner dapperQueriesRunner,
        IHttpClientFactory httpClientFactory,
        ILogger<CasasciusTrackerCsvReader> logger)
    {
        this.applicationSettings = applicationSettings;
        this.adoQueriesRunner = adoQueriesRunner;
        this.dapperQueriesRunner = dapperQueriesRunner;
        this.httpClientFactory = httpClientFactory;
        this.logger = logger;
    }

    /// <summary>
    /// Import CSV data file generated by Casascius Tracker (https://casasciustracker.com/)
    /// </summary>
    /// <remarks>
    /// Performs direct import of the file into DuckDb database. <br/>
    /// WARNING: It is very important that DuckDb <see cref="DuckDbSettings.HomeDirectory"/> and <see cref="ApplicationSettings.DataFolder"/> values match!
    /// </remarks>
    public async Task<bool> ImportStreamUsingTempFile(Stream stream, CancellationToken cancellationToken = default)
    {
        // Note: This method is very fast because it uses DuckDb's "read CSV" feature

        var dataFolder = applicationSettings.Value.DataFolder;
        var dataCsvName = Path.Combine(dataFolder, DEFAULT_DATA_CSV_NAME);

        try
        {
            await using (var fileStream = File.OpenWrite(dataCsvName))
                await stream.CopyToAsync(fileStream, cancellationToken);

            var result = await adoQueriesRunner.ImportCasasciusCoinsFromFile(DEFAULT_DATA_CSV_NAME, cancellationToken);

            File.Delete(dataCsvName);

            return result;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to process Casascius coins");
            return false;
        }
    }

    /// <summary>
    /// Downloads the latest CSV export from Casascius Tracker (https://casasciustracker.com/) and imports it using a temporary file.
    /// </summary>
    public async Task<bool> DownloadAndImportLatestSnapshot(CancellationToken cancellationToken = default)
    {
        const string CASASCIUS_TRACKER_CSV_EXPORT_ENDPOINT = "https://casasciustracker.com/export/csv/";
        try
        {
            using var http = httpClientFactory.CreateClient();
            http.DefaultRequestHeaders.UserAgent.ParseAdd("CasasciusHelper/1.0");

            using var response = await http.GetAsync(CASASCIUS_TRACKER_CSV_EXPORT_ENDPOINT, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
            response.EnsureSuccessStatusCode();

            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await ImportStreamUsingTempFile(stream, cancellationToken);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to download and import Casascius coins data snapshot");
            return false;
        }
    }

    /// <summary>
    /// Import CSV data file generated by Casascius Tracker (https://casasciustracker.com/)
    /// </summary>
    /// <remarks>
    /// Performs per-line (multiple INSERT statements) import of the file into DuckDb database. <br/>
    /// WARNING: This method is very flow</remarks>
    [Obsolete]
    public async Task ImportStream(Stream stream, CancellationToken cancellationToken = default)
    {
        const int DATABASE_BATCH_SIZE = 10000;

        using var reader = new StreamReader(stream);

        var batch = new List<CasasciusCoin>(DATABASE_BATCH_SIZE);
        var firstLine = true;
        string? line;
        while ((line = await reader.ReadLineAsync(cancellationToken)) is not null)
        {
            if (firstLine)
            {
                firstLine = false;
                CheckCsvFileHeader(line);
                continue;
            }

            var dto = ParseCsvDataLine(line);
            if (dto is null)
                continue;

            batch.Add(dto);
            if (batch.Count == DATABASE_BATCH_SIZE)
            {
                await dapperQueriesRunner.ImportCasasciusCoins(batch, cancellationToken);
                batch.Clear();
            }
        }

        await dapperQueriesRunner.ImportCasasciusCoins(batch, cancellationToken);
    }

    /// <summary>
    /// Parse CSV data line into <see cref="CasasciusCoin"/> DTO/>
    /// </summary>
    private CasasciusCoin? ParseCsvDataLine(string? line)
    {
        if (string.IsNullOrWhiteSpace(line))
            return null;

        var dataLineParts = line.Split(',');
        if (dataLineParts.Length != EXPECTED_CSV_COLUMNS_NUMBER)
            throw new Exception($"Invalid CSV data line (wrong number of values): {dataLineParts.Length} instead of {EXPECTED_CSV_COLUMNS_NUMBER} (in line: '{line}')");

        if (!int.TryParse(dataLineParts[0], out var id))
            throw new Exception($"Invalid CSV data line (cannot parse 'Id'): '{dataLineParts[0]}' (in line: '{line}')");

        var address = dataLineParts[1];

        int? series;
        if (string.IsNullOrWhiteSpace(dataLineParts[2]))
            series = null;
        else if (!int.TryParse(dataLineParts[2], out var seriesValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Series'): '{dataLineParts[2]}' (in line: '{line}')");
        else
            series = seriesValue;

        var type = dataLineParts[3];

        var status = dataLineParts[4];
        if (!status.IsDefinedIn<CasasciusStatuses>())
            throw new Exception($"Invalid CSV data line (invalid 'Status' value): '{dataLineParts[4]}' (in line: '{line}')");
        var statusValue = status.GetEnumValueFor<CasasciusStatuses>();

        decimal? value;
        if (string.IsNullOrWhiteSpace(dataLineParts[5]))
            value = null;
        else if (!decimal.TryParse(dataLineParts[5], NumberStyles.Float | NumberStyles.AllowThousands, CultureInfo.InvariantCulture, out var valueValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Value'): '{dataLineParts[5]}' (in line: '{line}')");
        else
            value = RemoveTrailingZeroes(valueValue);

        if (!decimal.TryParse(dataLineParts[6], NumberStyles.Float | NumberStyles.AllowThousands, CultureInfo.InvariantCulture, out var balance))
            throw new Exception($"Invalid CSV data line (cannot parse 'Balance'): '{dataLineParts[6]}' (in line: '{line}')");
        else
            balance = RemoveTrailingZeroes(balance);

        int? createBlock;
        if (string.IsNullOrWhiteSpace(dataLineParts[7]))
            createBlock = null;
        else if (!int.TryParse(dataLineParts[7], CultureInfo.InvariantCulture, out var createBlockValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Create Block'): '{dataLineParts[7]}' (in line: '{line}')");
        else
            createBlock = createBlockValue;

        int? redeemBlock;
        if (string.IsNullOrWhiteSpace(dataLineParts[8]))
            redeemBlock = null;
        else if (!int.TryParse(dataLineParts[8], out var redeemBlockValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Redeem Block'): '{dataLineParts[8]}' (in line: '{line}')");
        else
            redeemBlock = redeemBlockValue;

        DateTime? createTime;
        if (string.IsNullOrWhiteSpace(dataLineParts[9]))
            createTime = null;
        else if (!long.TryParse(dataLineParts[9], out var createTimeValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Create Time'): '{dataLineParts[9]}' (in line: '{line}')");
        else
            createTime = ToDateTimeFromUnixTimeSeconds(createTimeValue);

        DateTime? redeemTime;
        if (string.IsNullOrWhiteSpace(dataLineParts[10]))
            redeemTime = null;
        else if (!long.TryParse(dataLineParts[10], out var redeemTimeValue))
            throw new Exception($"Invalid CSV data line (cannot parse 'Redeem Time'): '{dataLineParts[10]}' (in line: '{line}')");
        else
            redeemTime = ToDateTimeFromUnixTimeSeconds(redeemTimeValue);

        if (!long.TryParse(dataLineParts[11], out var updateTimeLong))
            throw new Exception($"Invalid CSV data line (cannot parse 'Update Time'): '{dataLineParts[11]}' (in line: '{line}')");
        var updateTime = ToDateTimeFromUnixTimeSeconds(updateTimeLong);

        var result = new CasasciusCoin
        {
            Id = id,
            Address = address,
            Series = series,
            Type = type,
            Status = status,
            StatusValue = statusValue,
            Value = value,
            Balance = balance,
            CreateBlock = createBlock,
            RedeemBlock = redeemBlock,
            CreateTime = createTime,
            RedeemTime = redeemTime,
            UpdateTime = updateTime
        };

        return result;
    }

    /// <summary>
    /// Trivial check of CSV file data format
    /// </summary>
    private void CheckCsvFileHeader(string? line)
    {
        if (line != EXPECTED_CSV_FILE_HEADER)
            throw new Exception($"Invalid CSV data header: '{line}'");
    }

    private static decimal RemoveTrailingZeroes(decimal value)
        => value / 1.000000000000000000000000000000000m;

    /// <summary>
    /// Converts Unix Epoch seconds timestamp, UTC
    /// </summary>
    private static DateTime ToDateTimeFromUnixTimeSeconds(long offsetInSeconds)
        => DateTimeOffset.FromUnixTimeSeconds(offsetInSeconds).UtcDateTime; // UTC kind
}
