<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup Label="External references">
        <PackageReference Include="Dapper" />
        <PackageReference Include="DuckDB.NET.Data.Full" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup Label="Internal references">
        <ProjectReference Include="..\Casascius.Coins\Casascius.Coins.csproj" />
    </ItemGroup>

    <ItemGroup Label="Tests related references">
        <!-- Allow Tests project to "see" internal classes -->
        <InternalsVisibleTo Include="$(AssemblyName).Tests" />
        <InternalsVisibleTo Include="$(AssemblyName).Integration.Tests" />
        <!-- NSubstitute requirement for "internal" classes -->
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

</Project>
